feat: add weserv provider
nuxt/image pull request #1019
Opened 2023-09-30 11:09 UTC by nandi95

Most options are in the keymap, the documentation is just a link to the website. That could be improved but frankly that's a lot of work. Maybe someone can put ai to use and summaries the doc for the provider documentation

Recreated as per: https://github.com/nuxt/image/pull/962#issuecomment-1740714317

2023-10-02 10:14 UTC, danielroe commented on docs/content/3.providers/weserv.md
> +In addition to `height` and `width`, the Weserv provider numerous modifiers documentation [here](https://images.weserv.nl/docs/quick-reference.html/).
```suggestion
In addition to `height` and `width`, the Weserv provider numerous modifiers documentation [here](https://images.weserv.nl/docs/quick-reference.html).
```

2023-10-02 10:21 UTC, danielroe requested changes
Would you be able to add a few test cases for `weserv` in `playground/providers.ts`, `test/unit/providers.test.ts` and `test/providers.ts`? 🙏

2023-10-02 22:25 UTC, nandi95 commented
> Would you be able to add a few test cases for `weserv` in `playground/providers.ts`, `test/unit/providers.test.ts` and `test/providers.ts`? 🙏

<img width="1371" alt="Screenshot 2023-10-02 at 23 02 05" src="https://github.com/nuxt/image/assets/41805560/ea1fdc6c-753a-4f9d-98ba-19d31f929466">


I can't seem to run the tests. I installed with pnpm and run the test with it but I get the above.

2023-10-02 22:25 UTC, danielroe commented
You can try running `pnpm dev:prepare` first.

2023-10-03 10:20 UTC, nandi95 commented
I know the correct url is generated, and when testing it by pasting it into the browser, I get the result I expected yet. The ssr and no-ssr tests are not working. Can you perhaps help me on this front?

2023-10-05 09:02 UTC, kleisauke commented
As per the request made in https://github.com/nuxt/image/pull/962#issuecomment-1706726140, I'd like to provide my feedback:
- Please consider replacing `weserve` with `weserv`.
- Currently, `https://wsrv.nl` is hard-coded, and there's no flexibility to modify it. It's worth noting that many websites host their own solutions using our open-source code.

2023-12-17 07:56 UTC, danielroe approved these changes

2023-12-18 15:18 UTC, merged