chore(cloudimage): add condition if url startwith http for cloudimage
nuxt/image pull request #1028
Opened 2023-10-03 10:33 UTC by joffreyBerrier

2023-10-03 10:47 UTC, danielroe commented on src/runtime/providers/cloudimage.ts
>    }
I think we can slightly simplify this:

```suggestion
  const query = (operations ? ('?' + operations) : '')

  if (src.startsWith('http')) {
    return {
      url: src + query
    }
  }

  return {
    url: joinURL(cdnURL, baseURL, src) + query
  }
```

2023-10-03 10:47 UTC, danielroe commented on src/runtime/providers/cloudimage.ts
> +  if (src.startsWith('http')) {
Can we perhaps use a more precise test? for example, this would match `http-some-file.png`.

2023-10-03 10:48 UTC, danielroe requested changes
Thank you ❤️ 

I don't think we need to update other providers in this PR.

Could you update the check on `src` to make it a bit more precise? 🙏

2023-10-03 12:36 UTC, danielroe approved these changes
this looks good to me, thank you 👌

2023-10-03 12:37 UTC, danielroe approved these changes
this looks good to me, thank you 👌

2023-10-04 10:32 UTC, Atinux approved these changes

2023-10-04 10:33 UTC, merged